### ISSUE TITLE
Google hasn’t verified this app

### ISSUE THREAD

**Issue by alexandrereol** [sidhq/SID#5]
Hi there SID team,
as of now linking a SID account with Google Drive forwards to the following screen:

![CleanShot 2023-07-16 at 21 39 35@2x](https://github.com/sidhq/SID/assets/81623991/268ff93a-9a1b-493f-a164-c50d319ee022)

While it is possible to continue nevertheless, it can be scary for users to see such a message.

**Comment by gvilums** [comment]
We're aware, verification should be finalized by tomorrow

**Comment by ruflair** [comment]
It's verified now!
